// Generated by CoffeeScript 1.8.0
var __slice = [].slice;

define(function(require, exports, module) {
  'use strict';
  var Collection, Operation, Promise, Utils;
  Utils = require('lib/utils');
  Operation = require('lib/operation');
  Promise = require('lib/promise');
  Collection = (function() {

    /*
     *  in LocalDB, only use LocalDB to get a collection.
     *  db = new LocalDB('foo')
     *  var collection = db.collection('bar')
     */
    function Collection(collectionName, engine) {
      this.engine = engine;
      this.name = "" + engine.name + "_" + collectionName;
    }


    /*
     *  get data and tranfer into object from localStorage/sessionStorage
     */

    Collection.prototype.deserialize = function(callback) {
      return this.engine.getItem(this.name, function(data, err) {
        return callback(Utils.parse(data), err);
      });
    };


    /*
     *  save data into localStorage/sessionStorage
     *  when catching error in setItem(), delete the oldest data and try again.
     */

    Collection.prototype.serialize = function(data, callback) {
      return this.engine.setItem(this.name, Utils.stringify(data), callback);
    };


    /*
     *  delete this collection
     */

    Collection.prototype.drop = function(callback) {
      var promiseFn, self;
      self = this;
      promiseFn = function(resolve, reject) {
        return self.engine.removeItem(self.name, function(err) {
          if (callback != null) {
            callback(err);
          }
          if (err != null) {
            return reject(err);
          } else {
            return resolve();
          }
        });
      };
      return new Promise(promiseFn);
    };


    /*
     *  insert data into collection
     */

    Collection.prototype.insert = function() {
      var callback, options, paras, promiseFn, rowData, self, _ref;
      rowData = arguments[0], paras = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      _ref = Utils.parseParas(paras), options = _ref[0], callback = _ref[1];
      self = this;
      promiseFn = function(resolve, reject) {
        return self.deserialize(function(data, err) {
          if (err != null) {
            if (callback != null) {
              callback(err);
            }
            return reject(err);
          } else {
            data = Operation.insert(data, rowData, options);
            return self.serialize(data, function(err) {
              if (callback != null) {
                callback(err);
              }
              if (err != null) {
                return reject(err);
              } else {
                return resolve();
              }
            });
          }
        });
      };
      return new Promise(promiseFn);
    };


    /*
     *  update collection
     */

    Collection.prototype.update = function() {
      var actions, callback, options, paras, promiseFn, self, _ref;
      actions = arguments[0], paras = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      _ref = Utils.parseParas(paras), options = _ref[0], callback = _ref[1];
      self = this;
      promiseFn = function(resolve, reject) {
        return self.deserialize(function(data, err) {
          if (err) {
            if (callback != null) {
              callback(err);
            }
            return reject(err);
          } else {
            data = Operation.update(data, actions, options);
            return self.serialize(data, function(err) {
              if (callback != null) {
                callback(err);
              }
              if (err != null) {
                return reject(err);
              } else {
                return resolve();
              }
            });
          }
        });
      };
      return new Promise(promiseFn);
    };


    /*
     *  remove data from collection
     */

    Collection.prototype.remove = function() {
      var callback, options, paras, promiseFn, self, _ref;
      paras = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _ref = Utils.parseParas(paras), options = _ref[0], callback = _ref[1];
      self = this;
      promiseFn = function(resolve, reject) {
        return self.deserialize(function(data, err) {
          if (err != null) {
            if (callback != null) {
              callback(err);
            }
            return reject(err);
          } else {
            data = Operation.remove(data, options);
            return self.serialize(data, function(err) {
              if (callback != null) {
                callback(err);
              }
              if (err != null) {
                return reject(err);
              } else {
                return resolve();
              }
            });
          }
        });
      };
      return new Promise(promiseFn);
    };


    /*
     * find data from collection
     */

    Collection.prototype.find = function() {
      var callback, options, paras, promiseFn, self, _ref;
      paras = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _ref = Utils.parseParas(paras), options = _ref[0], callback = _ref[1];
      self = this;
      promiseFn = function(resolve, reject) {
        return self.deserialize(function(data, err) {
          if (err != null) {
            if (callback != null) {
              callback([], err);
            }
            return reject(err);
          } else {
            data = Operation.find(data, options);
            if (callback != null) {
              callback(data, err);
            }
            if (err != null) {
              return reject(err);
            } else {
              return resolve(data);
            }
          }
        });
      };
      return new Promise(promiseFn);
    };


    /*
     *  find data and only return one data from collection
     */

    Collection.prototype.findOne = function() {
      var callback, options, paras, promiseFn, self, _ref;
      paras = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      _ref = Utils.parseParas(paras), options = _ref[0], callback = _ref[1];
      options.limit = 1;
      self = this;
      promiseFn = function(resolve, reject) {
        return self.deserialize(function(data, err) {
          if (err != null) {
            if (callback != null) {
              callback(void 0, err);
            }
            return reject(err);
          } else {
            data = Operation.find(data, options);
            if (callback != null) {
              callback(data[0], err);
            }
            if (err != null) {
              return reject(err);
            } else {
              return resolve(data[0]);
            }
          }
        });
      };
      return new Promise(promiseFn);
    };

    return Collection;

  })();
  return module.exports = Collection;
});
