// Generated by CoffeeScript 1.7.1
'use strict';
var Engine;

Engine = (function() {
  function Engine(type) {
    this.type = type === 2 ? 2 : 1;
  }

  Engine.prototype.key = function(name) {
    if (this.type === 1) {
      return sessionStorage.key(name);
    }
    if (this.type === 2) {
      return localStorage.key(name);
    }
  };

  Engine.prototype.size = function() {
    if (this.type === 1) {
      return sessionStorage.length;
    }
    if (this.type === 2) {
      return localStorage.length;
    }
  };

  Engine.prototype.setItem = function(key, val) {
    if (this.type === 1) {
      return sessionStorage.setItem(key, val);
    }
    if (this.type === 2) {
      return localStorage.setItem(key, val);
    }
  };

  Engine.prototype.getItem = function(key) {
    if (this.type === 1) {
      return sessionStorage.getItem(key);
    }
    if (this.type === 2) {
      return localStorage.getItem(key);
    }
  };

  Engine.prototype.removeItem = function(key) {
    if (this.type === 1) {
      return sessionStorage.removeItem(key);
    }
    if (this.type === 2) {
      return localStorage.removeItem(key);
    }
  };

  return Engine;

})();

module.exports = Engine;
