// Generated by CoffeeScript 1.7.1
'use strict';
var Find, Projection, Utils, Where;

Where = require('./where');

Utils = require('./utils');

Projection = require('./projection');

Find = function(data, options) {
  var d, limit, projection, result, where, _i, _len;
  where = options.where || {};
  projection = options.projection || {};
  limit = options.limit || -1;
  result = [];
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    d = data[_i];
    if (!(Where(d, where))) {
      continue;
    }
    if (limit === 0) {
      break;
    }
    limit -= 1;
    result.push(d);
  }
  return Projection.generate(result, projection);
};

module.exports = Find;
