// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  'use strict';
  var hasIframe;
  hasIframe = (function() {
    var iframe;

    iframe = null;

    function hasIframe(src) {
      var allFrame, frames, self, _i, _len;
      this.src = src;
      self = this;
      allFrame = document.getElementsByTagName("iframe");
      for (_i = 0, _len = allFrame.length; _i < _len; _i++) {
        frames = allFrame[_i];
        if (frames.src === self.src) {
          iframe = frames;
          break;
        }
      }
      return iframe;
    }

    return hasIframe;

  })();
  return module.exports = hasIframe;
});
