// Generated by CoffeeScript 1.7.1
define(function(require, exports, module) {
  'use strict';
  var Iframe;
  return Iframe = (function() {
    function Iframe(origin) {
      this.origin = origin;
    }

    Iframe.prototype.create = function(content) {
      if (document.getElementById(this.origin) != null) {
        return;
      }
      this.ifrm = document.createElement("IFRAME");
      this.ifrm.setAttribute("src", this.origin);
      this.ifrm.setAttribute("id", this.origin);
      this.ifrm.style.width = "1px";
      this.ifrm.style.height = "1px";
      this.ifrm.style.display = "none";
      document.body.appendChild(this.ifrm);
    };

    Iframe.prototype.remove = function() {
      return this.ifrm.parentElement.removeChild(this.ifrm);
    };

    return Iframe;

  })();
});
