// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  'use strict';
  var Iframe, hasIframe;
  hasIframe = require("lib/has-iframe");
  Iframe = (function() {
    function Iframe(src) {
      var iframe, self;
      this.src = src;
      self = this;
      iframe = new hasIframe(self.src);
      if (iframe != null) {
        return iframe;
      } else {
        iframe = document.createElement("iframe");
        iframe.src = self.config.src;
        iframe.style.display = "none";
        document.body.appendChild(iframe);
        return iframe;
      }
    }

    return Iframe;

  })();
  return module.exports = Iframe;
});
