// Generated by CoffeeScript 1.7.1
'use strict';
var Insert, Utils, Where;

Where = require('./where');

Utils = require('./utils');

Insert = function(data, rowData, options) {
  var d, _i, _len;
  if (Utils.isArray(rowData)) {
    for (_i = 0, _len = rowData.length; _i < _len; _i++) {
      d = rowData[_i];
      if (!(Utils.isObject(d))) {
        continue;
      }
      if (d._id == null) {
        d._id = Utils.createObjectId();
      }
      data.push(d);
    }
  } else if (Utils.isObject(rowData)) {
    if (rowData._id == null) {
      rowData._id = Utils.createObjectId();
    }
    data.push(rowData);
  }
  return data;
};

module.exports = Insert;
