// Generated by CoffeeScript 1.7.1
'use strict';
var Projection;

Projection = {};

Projection.generate = function(data, projection) {
  var d, key, p, result, value, _i, _len;
  if (JSON.stringify(projection) === "{}") {
    return data;
  }
  result = [];
  for (_i = 0, _len = result.length; _i < _len; _i++) {
    d = result[_i];
    p = {};
    for (key in projection) {
      value = projection[key];
      if (value === 1) {
        p[key] = d[key];
      }
    }
    result.push(r);
  }
  return result;
};

module.exports = Projection;
