// Generated by CoffeeScript 1.7.1
'use strict';
var Remove, Utils, Where;

Where = require('./where');

Utils = require('./utils');

Remove = function(data, options) {
  var d, flag, multi, result, where, _i, _len;
  where = options.where || {};
  multi = options.multi || false;
  result = [];
  flag = false;
  for (_i = 0, _len = data.length; _i < _len; _i++) {
    d = data[_i];
    if (flag) {
      result.push(d);
      continue;
    }
    if (Where(d, where)) {
      if (multi) {
        flag = true;
      }
      continue;
    }
    result.push(d);
  }
  return result;
};

module.exports = Remove;
