// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  'use strict';
  var SendMessage, Utils;
  Utils = require('lib/utils');
  SendMessage = (function() {
    function SendMessage(data, src) {
      var iframe, self;
      this.data = data;
      this.src = src;
      self = this;
      iframe = Utils.getIframe(this.src);
      if (iframe != null) {
        iframe.contentWindow.postMessage(this.data, this.src);
      } else {
        iframe = Utils.createIfram(this.src);
        iframe.onload = function() {
          return iframe.contentWindow.postMessage(self.data, self.src);
        };
      }
    }

    return SendMessage;

  })();
  return module.exports = SendMessage;
});
