// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  'use strict';
  var Iframe, hasIframe, sendMessage;
  hasIframe = require("lib/has-iframe");
  Iframe = require("lib/iframe");
  sendMessage = (function() {
    function sendMessage(data, src) {
      var iframe, self;
      this.data = data;
      this.src = src;
      self = this;
      hasIframe = new hasIframe(self.src);
      iframe = new Iframe(self.src);
      if (hasIframe != null) {
        iframe.contentWindow.postMessage(data, self.src);
      } else {
        iframe.onload = function() {
          return iframe.contentWindow.postMessage(data, self.src);
        };
      }
    }

    return sendMessage;

  })();
  return module.exports = sendMessage;
});
