// Generated by CoffeeScript 1.7.1
define(function(require, exports, module) {
  'use strict';
  var Support, mod;
  mod = 'lST$*@?';
  Support = {};
  Support.localstorage = function() {
    var e;
    try {
      localStorage.setItem(mod, mod);
      localStorage.removeItem(mod);
      return true;
    } catch (_error) {
      e = _error;
      return false;
    }
  };
  Support.sessionstorage = function() {
    var e;
    try {
      sessionStorage.setItem(mod, mod);
      sessionStorage.removeItem(mod);
      return true;
    } catch (_error) {
      e = _error;
      return false;
    }
  };
  Support.postmessage = function() {
    return !!postMessage;
  };
  Support.websqldatabase = function() {
    return !!openDatabase;
  };
  Support.indexedDB = function() {
    return !!(indexedDB || webkitIndexedDB || mozIndexedDB || OIndexedDB || msIndexedDB);
  };
  Support.applicationcache = function() {
    return !!applicationCache;
  };
  Support.userdata = function() {
    return !!document.documentElement.addBehavior;
  };
  return module.exports = Support;
});
