// Generated by CoffeeScript 1.8.0
define(function(require, exports, module) {
  "use strict";
  var Promise;
  Promise = require("lib/promise");
  return describe("Promise", function() {
    return it("Init", function() {
      var promise;
      promise = new Promise(function(resolve, reject) {
        return resolve(100);
      });
      return promise.then(function(x) {
        return expect(x).toEqual(100);
      });
    });
  });
});
