// Generated by CoffeeScript 1.7.1
define(function(require, exports, module) {
  "use strict";
  var Promise;
  Promise = require("lib/promise");
  return describe("Promise", function() {
    return it("Init", function() {
      var promise;
      console.log("Promise Init");
      promise = new Promise(function(resolve, reject) {
        return resolve(100);
      });
      return promise.then(function(x) {
        console.log("Promise:then done!!!");
        return expect(x).toEqual(100);
      });
    });
  });
});
