// Generated by CoffeeScript 1.7.1
module.exports = function(config) {
  var configuration;
  configuration = {
    basePath: '',
    frameworks: ['jasmine', 'requirejs'],
    files: [
      {
        pattern: 'src/**/*.js',
        included: false
      }, {
        pattern: 'test/**/*Spec.js',
        included: false
      }, 'test/test-main.js'
    ],
    exclude: [],
    preprocessors: {
      "src/**/*.js": "coverage"
    },
    reporters: ['progress', 'coverage'],
    coverageReporter: {
      type: "lcov",
      dir: "coverage/"
    },
    plugins: ['karma-jasmine', 'karma-requirejs', 'karma-chrome-launcher', 'karma-phantomjs-launcher', 'karma-firefox-launcher', 'karma-ie-launcher', 'karma-coverage'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['Chrome', 'PhantomJS', 'Firefox'],
    customLaunchers: {
      Chrome_travis_ci: {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    },
    singleRun: false,
    captureTimeout: 6000
  };
  if (process.env.TRAVIS) {
    configuration.browsers = ['Chrome_travis_ci', 'PhantomJS', 'Firefox'];
  }
  return config.set(configuration);
};
