// Generated by CoffeeScript 1.7.1
'use strict';
var Collection, LocalDB, db, expect;

expect = require('expect.js');

LocalDB = require('../src/localdb.js');

Collection = require('../src/lib/collection.js');

db = new LocalDB("foo");

describe('Collection', function() {
  return it('Collection Init', function() {
    var collection;
    collection = db.collection("bar");
    expect(collection).to.be.ok();
    collection = new Collection("bar", db);
    return expect(collection).to.be.ok();
  });
});
